version: "3.4"
services:
  mongo:
    image: mongo:bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
   
  api: 
    container_name: api
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs
    build: .
    ports:
      - 3000:3000